app = "subgraph-users"
primary_region = "ewr"

[build]

[http_service]
internal_port = 4002
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
